{"name": "test_login[case2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "self = <TestCases.pytest.test_dome.TestLogin object at 0x000001544DAC5358>\ncase = {'expect_data': '{\"code\": 2,\"msg\": \"账号或密码错误.\"}', 'id': 3, 'method': 'patch', 'request_data': '{\"account\":\"mayc\",\"pwd\":\"123456\"}', ...}\n\n    def test_login(self,case):\n        print(\"执行第{}条用例：{}\".format(case[\"id\"], case[\"title\"]))\n        print(\"测试数据为：\",case)\n    \n        respon = send_requests(case[\"method\"], case[\"url\"], data=case[\"request_data\"])\n        print(\"测试结果为：\", respon.json())\n        expect_data = json.loads(case[\"expect_data\"])\n        try:\n>           assert respon.json()[\"code\"]!=expect_data[\"code\"]\nE           assert 2 != 2\n\nTestCases\\pytest\\test_dome.py:30: AssertionError"}, "parameters": [{"name": "case", "value": "{'id': 3, 'title': '登录失败-密码错误', 'method': 'patch', 'url': '/kvp_mps/v1/login', 'request_data': '{\"account\":\"mayc\",\"pwd\":\"123456\"}', 'expect_data': '{\"code\": 2,\"msg\": \"账号或密码错误.\"}'}"}], "start": 1597982280607, "stop": 1597982280695, "uuid": "c06313bf-f4d1-4fa2-9254-b351b9f118fe", "historyId": "faa6cadfae82b202dbf682d4eb5d2f98", "testCaseId": "3508b8cb4a6f338d1140ad49bea185dd", "fullName": "TestCases.pytest.test_dome.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "TestCases.pytest"}, {"name": "suite", "value": "test_dome"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "KST-CSB-lintt"}, {"name": "thread", "value": "36708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.pytest.test_dome"}]}